### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [zunichky/week5_layout#1]
It looks like the hosted URL is just pointing to the [*Build a simple Sinatra app* skill](http://codekwondo.herokuapp.com/skills/19) instead of your Heroku app. Can you update the showcase and let me know when it's done?

**Comment by zunichky** [comment]
oops I’m not sure how that happened. Should be updated to the right url now

**Comment by chrisvfritz** [comment]
:+1: Much better! Nice use of `content_for`. :tada: 

## Points of improvement for future projects

### Ruby indentation

The standard indentation for Ruby (`.rb`) files is actually with two-space soft-tabs rather than hard-tabs. See if you can update your text editor to use two-space soft-tabs for all Ruby files. If you have trouble figuring it out, [this page may be helpful](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md). If it's not, just let me know and I'll be happy to point you in the right direction.
